// Dummy data for testimonials
export const testimonials = [
  { id: 1, user: "Gohan", rating: 4, comment: "Great service!" },
  { id: 2, user: "Trunks", rating: 5, comment: "Excellent experience!" },
  { id: 3, user: "Vegeta", rating: 4, comment: "Good product!" },
  { id: 4, user: "Goku", rating: 5, comment: "Amazing!" },
  { id: 5, user: "Bulma", rating: 5, comment: "WOW 😲!" },
  { id: 6, user: "Krillin", rating: 4, comment: "Very satisfying!" },
  { id: 7, user: "Piccolo", rating: 5, comment: "Highly recommend!" },
  {
    id: 8,
    user: "Chi-Chi",
    rating: 3,
    comment: "Pretty good, but could be better.",
  },
  { id: 9, user: "Yamcha", rating: 4, comment: "Nice work, I'll be back!" },
  {
    id: 10,
    user: "Master Roshi",
    rating: 5,
    comment: "Fantastic! Keep it up!",
  },
  {
    id: 11,
    user: "Tien",
    rating: 4,
    comment: "Solid performance, very pleased.",
  },
  {
    id: 12,
    user: "Roshi",
    rating: 3,
    comment: "It was okay, nothing extraordinary.",
  },
  {
    id: 13,
    user: "Maron",
    rating: 5,
    comment: "Absolutely fantastic service!",
  },
  { id: 14, user: "Dende", rating: 5, comment: "Perfect in every way!" },
  {
    id: 15,
    user: "Lunch",
    rating: 4,
    comment: "Really good, will definitely recommend.",
  },
  {
    id: 16,
    user: "Krilin",
    rating: 4,
    comment: "Very impressive, would use again.",
  },
  {
    id: 17,
    user: "Goten",
    rating: 5,
    comment: "Top-notch service, highly satisfied!",
  },
  { id: 18, user: "Videl", rating: 4, comment: "Great value for the price." },
  {
    id: 19,
    user: "Android 18",
    rating: 5,
    comment: "Exceptional experience, highly recommend!",
  },
  {
    id: 20,
    user: "Babidi",
    rating: 3,
    comment: "Good, but has room for improvement.",
  },
  {
    id: 21,
    user: "Supreme Kai",
    rating: 5,
    comment: "Outstanding! Exceeded expectations!",
  },
  {
    id: 22,
    user: "Yajirobe",
    rating: 4,
    comment: "Quite good, will definitely return.",
  },
  {
    id: 23,
    user: "Mr. Satan",
    rating: 5,
    comment: "Awesome experience, couldn't be happier!",
  },
  {
    id: 24,
    user: "Jaco",
    rating: 4,
    comment: "Solid performance, would recommend.",
  },
  {
    id: 25,
    user: "Fasha",
    rating: 5,
    comment: "Remarkable service, top marks!",
  },
  {
    id: 26,
    user: "Radditz",
    rating: 3,
    comment: "Average, but still acceptable.",
  },
  {
    id: 27,
    user: "Broly",
    rating: 5,
    comment: "Incredible! Truly top-tier service.",
  },
  {
    id: 28,
    user: "Pan",
    rating: 4,
    comment: "Very good, had a pleasant experience.",
  },
  {
    id: 29,
    user: "Ginyu",
    rating: 5,
    comment: "Fantastic all around, would recommend to anyone!",
  },
  {
    id: 30,
    user: "Zarbon",
    rating: 4,
    comment: "Impressed with the quality, will come again.",
  },
];
